MQTT_BROKER = "192.168.0.7"
MQTT_PORT = 1883

TOPIC_TEMPERATURE = "sensor/temperature"
TOPIC_LIGHT       = "sensor/light"
TOPIC_SAFETY      = "sensor/safety"
TOPIC_ALARM       = "sensor/alarm"

PIN_LIGHT  = 17
PIN_HEAT   = 27
PIN_BUZZER = 23
PIN_FAN    = 18

LIGHT_THRESHOLD      = 5000
SAFETY_DISTANCE_MM   = 200
ALARM_DISTANCE_CM    = 20
TEMP_THRESHOLD_HEAT  = 24.5
TEMP_THRESHOLD_FAN   = 26.0